REPORT ZCORE_D21_P1.

*********** DAY 21 **************


"""" TOPICS - EXTERNAL SUBROUTINE -DEFINED IN EXTERNAL PROGRAMS(ANOTHER EXECUTABLE PROGRAMS / SUBROUTINE POOL) AND CALLED FROM OTHER PROGRAMS

FORMAT COLOR 1.

WRITE :/ 'INSIDE PROGRAM ZCORE_D21_P1 '.

*PERFORM SUB1.                                """"" SYNTAX ERROR - SUBROUTINE NOT FOUND IN SAME PROGRAM

PERFORM SUB1 IN PROGRAM ZCORE_D21_P2.

PERFORM SUB1(ZCORE_D21_P2).

FORMAT COLOR OFF.

ULINE.

FORMAT COLOR 2.

*PERFORM SUB2 IN PROGRAM ZCORE_D21_P2 .          """" RUNTIME ERROR - AS SUBROUTINE SUB2 EXPECTS 2 PARAMETERS
PERFORM SUB2 IN PROGRAM ZCORE_D21_P2 USING 20 10."""" TAKING 2 INPUT PARAMETERS X AND Y AS 20 AND 10.

"""" (OR)

PERFORM SUB2(ZCORE_D21_P2) USING 40 10.


FORMAT COLOR OFF.


ULINE.


"""" SUBROUTINE POOL - IS A CONTAINER OF EXTERNAL SUBROUTINE.

"""" CREATING SUBROUTINE POOL WITH NAME - ZCORE_D21_P3

FORMAT COLOR 3.

PERFORM SUB1 IN PROGRAM ZCORE_D21_P3.

FORMAT COLOR OFF.


FORMAT COLOR 4.
WRITE :/ 'THE TWO NUMBERS ARE 40 AND 10'.

PERFORM SUB2 IN PROGRAM ZCORE_D21_P3 USING 40 10.

FORMAT COLOR OFF.

FORMAT COLOR 5.

PERFORM SUB3 IN PROGRAM ZCORE_D21_P3 USING 40 10.

FORMAT COLOR OFF.
