REPORT ZCORE_D14_P1.


***************** SELECTION SCREEN TABBED BLOCK **************************


"""""""" TABBED BLOCK - TABBED BLOCK MEANS HAVING MULTIPLE TABS WITHIN SELECTION SCREEN. EACH OF TABBED BLOCK WILL HAVE SEPARATE SUB SCREEN.
""""""""                THERE SHOULD BE A DEFAULT TAB AND A SUB SCREEN ASSOCIATED WITH IT.



SELECTION-SCREEN BEGIN OF TABBED BLOCK TB1 FOR 5 LINES.
  SELECTION-SCREEN TAB (15) T1 USER-COMMAND FC1.                                  """""""" USER-COMMAND TO DEFINE FUNCTION CODE TO CHECK THE USER INTERACTION.
  SELECTION-SCREEN TAB (15) T2 USER-COMMAND FC2.                                  """""""" USER-COMMAND TO DEFINE FUNCTION CODE TO CHECK THE USER INTERACTION.


SELECTION-SCREEN END OF BLOCK TB1.

"""""""""""" NOW DESIGNING SUB SCREEN """"""""""""


SELECTION-SCREEN BEGIN OF SCREEN 100 AS SUBSCREEN.

   SELECTION-SCREEN COMMENT 8(30) LB1.                                    """"""""" SHOWING STATIC TEXT ON THE SCREEN AT 8 TH POSITION WITH 30 SPACES RESERVED.   \\
SELECTION-SCREEN END OF SCREEN 100.

SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN.

   SELECTION-SCREEN COMMENT 8(30) LB2.                                 """"""""" SHOWING STATIC TEXT ON THE SCREEN AT 8 TH POSITION WITH 30 SPACES RESERVED.   \\
SELECTION-SCREEN END OF SCREEN 200.



""""""""""" NOW LINKING SUBSCREEN WITH TABBED BLOCK """"""""""""""""""""""""


INITIALIZATION.

TB1-ACTIVETAB = 'FC2'.                                 """""""" TABBED BLOCKED IS HAVING PROPERTIES CALLED ACTIVETAB . NOW WANT TO ACTIVATE SECOND TAB BY DEFAULT.
TB1-DYNNR = '200'.                                      """""""" HOLD THE SCREEN NUMBER AS WE WANT TO ASSOCIATE THE SUBSCREEN
TB1-PROG = 'ZCORE_D14_P1'.                              """""""" FOR CHECKING IN WHICH PROGRAM IT HAS SUBSCREEN . CAN ALSO USE SY-REPID (FOR CURRENT PROGRAM)

T1 = 'TAB1'.
T2 = 'TAB2'.

LB1 = 'WELCOME TO SUBSCREEN 1'.

LB2 = 'WELCOME TO SUBSCREEN 2'.


""""""""""""""""""" NOW AT SELECTION SCREEN IS EVENT TRIGGERED WHENEVER THE USER CLICKS ON TAB BUTTON """""""""""""""""""""""
""""" DESIGNING AT SELECTIOMN SCREEN EVENT.

AT SELECTION-SCREEN.
  CASE SY-ucomm .
    WHEN 'FC1'.
      TB1-ACTIVETAB = 'FC1'.
      TB1-DYNNR = '100'.
      TB1-PROG = SY-REPID.

    WHEN 'FC2'.
      TB1-ACTIVETAB = 'FC2'.
      TB1-DYNNR = '200'.
      TB1-PROG = SY-REPID.

   ENDCASE.
   
   
   
