REPORT ZCORE_D21_P7.

************* DAY 21 PROG 7 (CALLING INCLUDE PROG FROM PROG 6). *****************
"""" TOPICS - INCLUDING SUBROUTINE DEFINITION FROM INCLUDE PROGRAM

INCLUDE ZCORE_D21_P6.           """" ERROR SINCE INCLUDE IS CALLED BEFORE PERFORM STATEMENT

START-OF-SELECTION.             """" USING THIS SINCE THERE IS INCLUDE PROG AND MODULE PROG


WRITE :/ 'INSIDE PROG 7'.



PERFORM SUB1.


*WRITE SY-tleng.                 """" USED TO PRINT THE ROW SIZE OR WIDTH OF INTERNAL TABLE
