REPORT ZCORE_D13_P3.

""""""""""""""""""""""""""""""  FOR DECLARING STANDARD STRUCTURE """"""""""""""""""
""""""" STANDARD STRUCTURE - DECLARED WITH TYPES KEYWORD.

TYPES : BEGIN OF GTY_EMP,
          EMPNO TYPE I,
          ENAME(20) TYPE C,
          EMPDESIG(15) TYPE C,
        END OF GTY_EMP.


DATA : WA_EMP1 TYPE gty_emp.

WA_EMP1-EMPNO = 6.
WA_EMP1-ENAME = 'RAHUL'.
WA_EMP1-EMPDESIG = 'MANAGER'.



WRITE :/ 'WA_EMP1 STRUCTURE'.

WRITE :/ WA_EMP1-EMPNO,  WA_EMP1-ENAME, WA_EMP1-ENAME.



"""""""""""""""" CAN CREATE ANY NUMBER OF WORK AREA FOR THE SAME TEMPLATE
""""""""" WORK AREA - CAN CREATE MUTIPLE WORK AREA FOR THE SAME STANDARD STRUCTURE.

ULINE.

DATA : WA_EMP2 TYPE GTY_EMP.

WRITE :/ 'WA_EMP2 STRUCTURE'.

WRITE :/ WA_EMP1-EMPNO,  WA_EMP1-ENAME, WA_EMP1-ENAME.


WA_EMP2 = WA_EMP1.

WRITE :/ 'WA_EMP2 STRUCTURE AFTER ASSIGING WA_EMP1 STRUCTURE'.

WRITE :/ WA_EMP1-EMPNO,  WA_EMP1-ENAME, WA_EMP1-ENAME.
