REPORT ZCORE_D17_P1.

************** DAY 17 ****************
"""" TOPICS - SORT BY DESCENDING, SORT BY
""""          

""""""""""" BELOW CODE COPIED FROM DAY 16 **************
""""""""""" CONTINUE OF DAY 16            """"""""""""""

*REPORT ZCORE_D16_P1.

*********** DAY 16 *********

""""" INTERNAL TABLES
""" TOPICS -

"" INTERNAL TABLE WITHOUT HEADER
"" INSERT
"" INSERT INTO INDEX.
"" APPEND LINES OF - FOR COPYING DATA FROM IT TO ANOTHER IT
"" SORT
"" WITH NON UNIQUE KEY

TYPES : BEGIN OF gty_emp,
          empno        TYPE i,
          ename(20)    TYPE c,
          empdesig(25) TYPE c,
        END OF gty_emp.

DATA GT_EMP1 TYPE TABLE OF GTY_EMP.       """" INTERNAL TABLE DECLARATION

* GT_EMP1-EMPNO = 4.      """' SYNTAX ERROR SINCE NOT DATA ALLOCATED AND NO HEADER.

DATA GS_EMP1 TYPE GTY_EMP.


"""" RECORD 1


CLEAR GS_EMP1.

GS_EMP1-EMPNO = 1.
GS_EMP1-ENAME = 'RAHUL PILLAI'.
GS_EMP1-EMPDESIG = 'CEO'.

APPEND GS_EMP1 TO GT_EMP1.

"""" RECORD 2

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 2.
GS_EMP1-ENAME = 'SURAJ PILLAI'.
GS_EMP1-EMPDESIG = 'DIRECTOR'.

APPEND GS_EMP1 TO GT_EMP1.

"""" RECORD 3

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'VASU PILLAI'.
GS_EMP1-EMPDESIG = 'MANAGER'.

APPEND GS_EMP1 TO GT_EMP1.

FORMAT COLOR 1.

WRITE :/ 'DATA IN GT_EMP1 IS'.

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.


CLEAR GS_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'AK'.
GS_EMP1-EMPDESIG = 'BOSS'.

INSERT GS_EMP1 INTO TABLE GT_EMP1.       """" INSERT STATEMENT INSTEAD OF APPEND STATEMENT

FORMAT COLOR 2.

ULINE.
WRITE :/ 'BY USING INSERT STATEMENT '.
LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 5.
GS_EMP1-ENAME = 'KA'.
GS_EMP1-EMPDESIG = 'TEAM LEAD'.

INSERT GS_EMP1 INTO GT_EMP1 INDEX 2.       """" INSERT STATEMENT INSTEAD OF APPEND STATEMENT THUS INSERT STATEMENT CAN INSERT THE RECORD AT ANY POSITION

FORMAT COLOR 3.

ULINE.
WRITE :/ 'BY USING INSERT WITH INDEX '.

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.


FORMAT COLOR OFF..
"""" DECLARING ONE MORE INTERNAL TABLE

*DATA : GT_EMP2 TYPE TABLE OF GTY_EMP WITH UNIQUE KEY EMPNO.      """" SYNTAX ERROR - UNIQUE KEY CAN ONLY BE USED WITH HASHED OR SORTED INTERNAL TABLE

"""" NOTE - WHILE DECLARING INTERNAL TABLES WE CAN SPECIFY THE KEY FIELDS THE KEY CAN BE 1) UNIQUE KEY OR 2)NON UNIQUE KEY
""""        > CAN CREATE STD INTERNAL TABLE WITH OR WITHOUT KEY


DATA : GT_EMP2 TYPE TABLE OF GTY_EMP WITH NON-UNIQUE KEY EMPNO.      """" ONLY NON UNIQUE KEY POSSIBLE


APPEND LINES OF GT_EMP1 TO GT_EMP2.

ULINE.

FORMAT COLOR 4.

WRITE :/ 'COPYING DATA FROM GT_EMP1 TO GT_EMP2 USING APPEND LINES OF STATEMENT '.

LOOP AT GT_EMP2 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.

FORMAT COLOR 5.

ULINE.

WRITE :/ 'USING DEFAULT SORT STATEMENT'.

SORT GT_EMP1.                                    """" SORT - USED TO ARRANGE DATA IN A ORDER

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.

FORMAT COLOR 6.

ULINE.

WRITE :/ 'USING DEFAULT SORT ON NON UNIQUE KEY FIELD IN GT_EMP2 '.

SORT GT_EMP2.                                    """" SORT - USED TO ARRANGE DATA IN A ORDER

LOOP AT GT_EMP2 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.



""""""""" START OF DAY 17 """"""""""""

"""" SORT BY
ULINE.

FORMAT COLOR 7.
WRITE :/ 'USING SORT BY KEY ON NON UNIQUE KEY FIELD IN GT_EMP2 '.

SORT GT_EMP2 BY EMPDESIG.                                    """" SORT BY - USED TO ARRANGE DATA IN A ORDER FOR A PARTICULAR FIELD.

LOOP AT GT_EMP2 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.

"""" SORT BY DESCENDING
ULINE.

FORMAT COLOR 1.
WRITE :/ 'USING SORT BY DESCENDING KEY ON NON UNIQUE KEY FIELD IN GT_EMP2 '.

SORT GT_EMP2 BY EMPDESIG DESCENDING.                                    """" SORT BY DESCENDING - USED TO ARRANGE DATA IN A DESCENDINGORDER FOR A PARTICULAR FIELD.

LOOP AT GT_EMP2 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.


"""" NOTE - BY DEFAULT ITS ALWAYS GONNA SORT IN ASSCENDING ORDER.

