REPORT ZCORE_D18_P2.


********** DAY 18 PROG 2  ************

"""" TOPICS - HASHED INTERNAL TABLE - USES HASHED ALOGORITHM > INDEXING IS NOT POSSIBLE ONLY SEARCHING IS POSSIBLE BASED ON THE KEY FIELD.ALSO USE HASHED INTERNAL TABLE FOR LARGE AMOUNT OF DATA.
""""                                  DOESN'T SUPPORT EXPLICIT / IMPLICIT INDEX OPERATIONS.
""""                                  IMPLICIT INDEX OPERATIONS - APPEND , READ WITH BINARY SEARCH.
""""                                  EXPLICIT INDEX OPERATIONS - INSERT WITH INDEX , READ WITH INDEX
""""







TYPES : BEGIN OF GTY_EMP,
          EMPNO TYPE I,
          ENAME(20) TYPE C,
          EMPDESIG(25) TYPE C,
        END OF GTY_EMP.


*DATA : GT_EMP1 TYPE SORTED TABLE OF GTY_EMP,     """" SYNTAX ERROR            """" NOTE - KEY IS MANDATORY IN HASHED INTERNAL TABLE
*       GS_EMP1 TYPE GTY_EMP.

DATA : GT_EMP1 TYPE HASHED TABLE OF GTY_EMP WITH UNIQUE KEY EMPNO,         """"  NOTE - HASHED INTERNAL KEY SUPPORTS ONLY UNIQUE KEY
       GS_EMP1 TYPE GTY_EMP.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 1.
GS_EMP1-ENAME = 'RAHUL'.
GS_EMP1-EMPDESIG = 'CEO'.

*APPEND GS_EMP1 TO GT_EMP1.                """" ERROR
INSERT GS_EMP1 INTO TABLE GT_EMP1.


CLEAR GS_EMP1.

GS_EMP1-EMPNO = 2.
GS_EMP1-ENAME = 'SURAJ'.
GS_EMP1-EMPDESIG = 'CTO'.

INSERT GS_EMP1 INTO TABLE GT_EMP1.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'SONU'.
GS_EMP1-EMPDESIG = 'MANAGER'.

*INSERT GS_EMP1 INTO GT_EMP1 INDEX 2.                        """" SYNTAX ERROR - NOT POSSIBLE WITH INDEX KEYWORD.
INSERT GS_EMP1 INTO TABLE GT_EMP1.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'MONU'.
GS_EMP1-EMPDESIG = 'MANAGER'.

*INSERT GS_EMP1 INTO GT_EMP1 INDEX 2.                        """" SYNTAX ERROR - NOT POSSIBLE WITH INDEX KEYWORD.
INSERT GS_EMP1 INTO TABLE GT_EMP1.                           """" IGNORES THE 2ND RECORD ADDED AND ADDS ONLY THE FIRST INSERT RECORD WITH THE SAME EMPNO.


FORMAT COLOR 1.

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.

ENDLOOP.

ULINE.

SORT GT_EMP1 BY ENAME.

FORMAT COLOR 2.

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.

ENDLOOP.
FORMAT COLOR OFF.
****
****CLEAR GS_EMP1.
****
****GS_EMP1-EMPNO = 3.
****GS_EMP1-ENAME = 'SONU'.
****GS_EMP1-EMPDESIG = 'DIRECTOR'.
****
*****APPEND GS_EMP1 TO GT_EMP1.                  """" RUNTIME ERROR - SHOULD ENSURE SORTING SEQUENCE BASED ON THE KEY FIELD.
****
****ULINE.
****
****FORMAT COLOR 2.
****
****INSERT GS_EMP1 INTO TABLE GT_EMP1.          """"  INSERT - WITH INSERT STATEMENT WE NEED NOT WORRY ABOUT THE SORTING SEQUENCE.
****
****LOOP AT GT_EMP1 INTO GS_EMP1.
****
****  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.
****
****ENDLOOP.
****
****FORMAT COLOR OFF.
****
****"""" NOTE - THUS INSERT STATEMENT IS PREFERED SINCE THEN WE WON'T NEED TO TAKE CARE OF THE DUPLICATE ENTRY
****
****"""" READ 3 RD RECORD   """" SHOWS INDEX SEARCH IS SUPPORTED IN SORTED INTERNAL TABLE.
****ULINE.
****FORMAT COLOR 3.
****CLEAR GS_EMP1.
****
****READ TABLE GT_EMP1 INTO GS_EMP1 INDEX 3.                            """" SYNTAX ERROR FOR READ WITH INDEX
****
****IF SY-SUBRC = 0.
****  WRITE :/ '3 RD RECORD FOUND'.
****  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.
****ELSE.
****  WRITE :/ '3RD RECORD NOT FOUND'.
****
****ENDIF.
****FORMAT COLOR OFF.
****
****
****"""" READ RECORD WITH EMPNO = 3
****ULINE.
****FORMAT COLOR 4.
****CLEAR GS_EMP1.
****
****READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 3.                            """" SEARCHING LINEAR - SEQUENTIAL SEARCH
****
****IF SY-SUBRC = 0.
****  WRITE :/ 'RECORD FOUND WITH EMPNO = 3'.
****  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.
****ELSE.
****  WRITE :/ 'RECORD NOT FOUND WITH EMPNO = 3'.
****
****ENDIF.
****FORMAT COLOR OFF.
****
****"""" READ RECORD WITH EMPNO = 2 WITH BINARY SEARCH
****ULINE.
****FORMAT COLOR 5.
****CLEAR GS_EMP1.
****
****READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 2 BINARY SEARCH.                            """" BINARY SEARCH - BETTER PERFORMANCE
****
****IF SY-SUBRC = 0.
****  WRITE :/ 'RECORD FOUND WITH EMPNO = 2'.
****  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.
****ELSE.
****  WRITE :/ 'RECORD NOT FOUND WITH EMPNO = 2'.
****
****ENDIF.
****FORMAT COLOR OFF.

