REPORT ZCORE_D20_P1.


************ DAY 20 *************

"""" TOPICS - PASSING INTERNAL TABLES AS PARAMETERS TO SUBROUTINE USING --- KEYWORD TABLES, DELETE STATEMENT, MODIFY GT_EMP1 FROM GS_EMP1.


TYPES : BEGIN OF GTY_EMP,
          EMPNO TYPE I,
          ENAME(20) TYPE C,
          EMPDESIG(25) TYPE C,
        END OF GTY_EMP.

DATA : GT_EMP1 TYPE TABLE OF GTY_EMP,
       GS_EMP1 TYPE GTY_EMP.



GS_EMP1-EMPNO = 1.
GS_EMP1-ENAME = 'RAHUL'.
GS_EMP1-EMPDESIG = 'CEO'.

APPEND GS_EMP1 TO GT_EMP1.

GS_EMP1-EMPNO = 2.
GS_EMP1-ENAME = 'SURAJ'.
GS_EMP1-EMPDESIG = 'EMPLOYEE'.

APPEND GS_EMP1 TO GT_EMP1.

GS_EMP1-EMPNO = 3.
GS_EMP1-ENAME = 'SONU'.
GS_EMP1-EMPDESIG = 'COO'.

APPEND GS_EMP1 TO GT_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'MONU'.
GS_EMP1-EMPDESIG = 'MANAGER'.

APPEND GS_EMP1 TO GT_EMP1.

FORMAT COLOR 1.

LOOP AT GT_EMP1 INTO GS_EMP1.
        WRITE :/ GS_EMP1-EMPNO,GS_EMP1-ENAME , GS_EMP1-EMPDESIG.
ENDLOOP.

FORMAT COLOR OFF.


""""" NOW PASSING INTERNAL TABLE AS A PARAMETER TO SUBROUTINE. """""

PERFORM SUB1 USING GT_EMP1.                                     """" USING - IS USED WHILE USING STD. DATA TYPES AND PARAMETERS.

ULINE.


"""" PASSING INTERNAL TABLES AS PARAMETERS TO SUBROUTINES.

FORMAT COLOR 2.
PERFORM SUB2 TABLES GT_EMP1.                                    """" WHENEVER USING OR PASSING INTERNAL TABLES AS PARAMETERS TO SUBROUTINE NEED TO USE TABLES KEYWORD.
FORMAT COLOR OFF.

ULINE.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 5.
GS_EMP1-ENAME = 'LAWRENCE'.
GS_EMP1-EMPDESIG = 'LAWYER'.
APPEND GS_EMP1 TO GT_EMP1.

FORMAT COLOR 3.
PERFORM SUB2 TABLES GT_EMP1.
FORMAT COLOR OFF.

ULINE.

"""" REQUIREMENT - PASSING INTERNAL TABLES AS PARAMETERS TO SUBROUTINE AND DELETE ALL THE MANAGERS

PERFORM SUB3 TABLES GT_EMP1.               """" NOTE- THE CHANGES DONE TO FORMAL INTERNAL TABLE WILL  AUTOMATICALLY REFLECT TO THE ACTUAL INTERNAL TABLE >>> NPOTHING BUT PASS BY REFERENCE



FORMAT COLOR 4.

WRITE :/ 'REQUIREMENT - PASSING INTERNAL TABLES AS PARAMETERS TO SUBROUTINE AND DELETE ALL THE MANAGERS'.
PERFORM SUB2 TABLES GT_EMP1.
FORMAT COLOR OFF.



FORMAT COLOR 5.
WRITE :/ 'REQUIREMENT - MODIFY INTERNAL TABLE WITH EMPLOYEE TO SR.EMPLOYEE'.
PERFORM SUB4 TABLES GT_EMP1.
FORMAT COLOR OFF.




"""" ALL THE SUBROUTINE FORMS DECLARED HERE

FORM SUB1 USING LT_EMP1.
*  LOOP AT LT_EMP1 INTO GS_EMP1.                                """" SYNTAX ERROR - LT_EMP1 IS NOT RECOGNISED AS AN INTERNAL TABLE.
*
*
*  ENDLOOP.
ENDFORM.


FORM SUB2 TABLES LT_EMP1.
  LOOP AT LT_EMP1 INTO GS_EMP1.
    WRITE :/ GS_EMP1-EMPNO,
           / GS_EMP1-ENAME,
           / GS_EMP1-EMPDESIG.

  ENDLOOP.


ENDFORM.

FORM SUB3 TABLES GT_EMP1 STRUCTURE GS_EMP1.                                   """" NOTE - WHENEVER YOU ARE MODIFYING OR DELETING THE DATA WE MUST SPECIFY THE ROW TYPE OF THE INTERNAL TABLE
  DELETE GT_EMP1 WHERE EMPDESIG = 'MANAGER'.                """"        ELSE YOU GET AN ERROR.
                                                            """"        SHOULD SPECIFY THE STRUCTURE

ENDFORM.


FORM SUB4 TABLES GT_EMP1 STRUCTURE GS_EMP1.
  CLEAR GS_EMP1.
  GS_EMP1-EMPDESIG = 'SR.EMPLOYEE'.
  MODIFY GT_EMP1 FROM GS_EMP1 TRANSPORTING EMPDESIG WHERE EMPDESIG = 'EMPLOYEE'.
  
  


ENDFORM.


"""" NOTE - WHENEVER USING DELETE OR MODIFY SHOULD SPECIFY THE STRUCTURE KEYWORD IN FORM.
