REPORT ZCORE_D17_P2.

************** DAY 17 PROGRAM 2 ****************
"""" TOPICS -
""""        READ STATEMENT ,SY-SUBRC, SY-TABIX, READ WITH INDEX , READ TABLE INDEX WITH TRANSPORTING FIELDS,
""""        READ TABLE WITH KEY AND BINARY SEARCH, READ TABLE WITH TRANSPORTING NO FIELDS








""""""""""" BELOW CODE COPIED FROM DAY 16 **************

*REPORT ZCORE_D16_P1.

TYPES : BEGIN OF gty_emp,
          empno        TYPE i,
          ename(20)    TYPE c,
          empdesig(25) TYPE c,
        END OF gty_emp.

DATA GT_EMP1 TYPE TABLE OF GTY_EMP WITH NON-UNIQUE KEY EMPNO.       """" INTERNAL TABLE DECLARATION

* GT_EMP1-EMPNO = 4.      """' SYNTAX ERROR SINCE NOT DATA ALLOCATED AND NO HEADER.

DATA GS_EMP1 TYPE GTY_EMP.


"""" RECORD 1


CLEAR GS_EMP1.

GS_EMP1-EMPNO = 1.
GS_EMP1-ENAME = 'RAHUL PILLAI'.
GS_EMP1-EMPDESIG = 'CEO'.

APPEND GS_EMP1 TO GT_EMP1.

"""" RECORD 2

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 2.
GS_EMP1-ENAME = 'SURAJ PILLAI'.
GS_EMP1-EMPDESIG = 'DIRECTOR'.

APPEND GS_EMP1 TO GT_EMP1.

"""" RECORD 3

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 4.
GS_EMP1-ENAME = 'VASU PILLAI'.
GS_EMP1-EMPDESIG = 'MANAGER'.

APPEND GS_EMP1 TO GT_EMP1.

CLEAR GS_EMP1.

GS_EMP1-EMPNO = 2.                                                  """" THIS SHOWS ITS ABLE TO HOLD DUPLICATE VALUE SINCE NON UNIQUE KEY IS THERE
GS_EMP1-ENAME = 'HELLO'.
GS_EMP1-EMPDESIG = 'CTO'.

APPEND GS_EMP1 TO GT_EMP1.

FORMAT COLOR 1.

WRITE :/ 'DATA IN GT_EMP1 IS'.

LOOP AT GT_EMP1 INTO GS_EMP1.

  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.


ENDLOOP.

FORMAT COLOR OFF.


ULINE.

"""" READ KEYWORD - IT WILL READ THE RECORD FROM BODY OF THE INTERNAL TABLE AND IF READ IS SUCCESFUL IT WILL POPULATE THE RECORD TO THE WORK AREA AND THEN IT WILL SET SY-SUBRC TO 0
CLEAR GS_EMP1.

READ TABLE GT_EMP1 INTO GS_EMP1 INDEX 2.

IF SY-SUBRC = 0.
  WRITE :/ '2RD RECORD IS FOUND '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.
ELSE.
  WRITE:/ '3RD RECORD READ FAILED'.

ENDIF.


"""" READ KEYWORD - BUT INTRESTED IN 5TH RECORD EMPLOYEE NUMBER AND EMPLOYEE NAME

"""" NOTE - BLINDLY SHOULD NOT USE THE READ STATEMENT

ULINE.

*SORT GT_EMP1.   """" IT STILL SORTS BY EMPLOYEE NUMBER SINCE ITS THE KEY FIELD

SORT GT_EMP1 BY EMPNO.


CLEAR GS_EMP1.

READ TABLE GT_EMP1 INTO GS_EMP1 INDEX 3 TRANSPORTING EMPNO ENAME.

IF SY-SUBRC = 0.
  WRITE :/ '3RD RECORD IS FOUND '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.                       """" ABLE TO READ THE READ THE RECORD AT A PARTICULAR INDEX WTIH REQUIRED FIELD.
ELSE.
  WRITE:/ 'the read FAILED'.

ENDIF.

"""" NOTE - BLINDLY SHOULD NOT USE THE READ STATEMENT

*SORT GT_EMP1.   """" IT STILL SORTS BY EMPLOYEE NUMBER SINCE ITS THE KEY FIELD.

********** READING TABEL WITH A PARTICULAR KEY FIELD AND EMPNO *****************

ULINE.

WRITE :/ 'SORT THE INTERNAL TABLE'.

SORT GT_EMP1 BY EMPNO.

CLEAR GS_EMP1.

READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 2.

IF SY-SUBRC = 0.
  WRITE :/ 'EMPNO WITH 2 IS FOUND  '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.                       """" ABLE TO READ THE READ THE RECORD AT A PARTICULAR INDEX WTIH REQUIRED FIELD.
ELSE.
  WRITE:/ 'the read FAILED'.

ENDIF.



ULINE.

WRITE :/ 'SORT THE INTERNAL TABLE'.

SORT GT_EMP1 BY EMPNO.

CLEAR GS_EMP1.

READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 124.

IF SY-SUBRC = 0.
  WRITE :/ 'EMPNO WITH 2 IS FOUND  '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.                       """" ABLE TO READ THE READ THE RECORD AT A PARTICULAR INDEX WTIH REQUIRED FIELD.
ELSE.

ENDIF.

WRITE:/ 'the read FAILED'.

"""" READ FAILED SINCE THERE IS NO RECORD WITH THE KEY 124.

**** NOW TO IMPROVE THE PERFORMANCE FURTHER USING BINARY SEARCH

ULINE.

WRITE :/ 'USING READ WIHT BINARY SEARCH'.

SORT GT_EMP1 BY EMPNO.

CLEAR GS_EMP1.

READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 4 BINARY SEARCH.                """" IMPROVES THE PERFORMANCE ELSE IT WOULD USE LINEAR SEARCH BY DEFAULT.

IF SY-SUBRC = 0.
  WRITE :/ 'EMPNO WITH 2 IS FOUND  '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.                       """" ABLE TO READ THE READ THE RECORD AT A PARTICULAR INDEX WTIH REQUIRED FIELD.
ELSE.
  WRITE:/ 'the read FAILED'.

ENDIF.

ULINE.

**** REQUIREMENT - TO CHECK IF EMPNO 4 IS AVAILABLE OR NOT
*CLEAR GS_EMP1.
*
*SORT GT_EMP1 BY EMPNO.

*READ TABLE GT_EMP1 INTO GS_EMP1 WITH KEY EMPNO = 3 TRANSPORTING NO FIELDS.      """" DON'T USE ANY INTO STATEMENT

READ TABLE GT_EMP1 WITH KEY EMPNO = 1 TRANSPORTING NO FIELDS.

IF SY-SUBRC = 0.
  WRITE :/ 'EMPNO WITH 1 IS FOUND  '.
  WRITE :/ GS_EMP1-EMPNO, GS_EMP1-ENAME, GS_EMP1-EMPDESIG.                       """" ABLE TO READ THE READ THE RECORD AT A PARTICULAR INDEX WTIH REQUIRED FIELD.
ELSE.
  WRITE:/ 'the read FAILED'.


ENDIF.

ULINE.

"""""" TO SHOW THAT SY-TABIX IS FOR INDEX ONLY
FORMAT COLOR 1.
DO 10 TIMES.

  WRITE :/  'HELLO', SY-TABIX.
ENDDO.

FORMAT COLOR OFF.




"""" HAPPY LEARNING ^_^ """"
