PROGRAM ZCORE_D21_P3.             """" PROGRAM KEYWORD FOR SUBROUTINE POOL

************ DAY 21 PROG 3 (SUBROUTINE POOL) ***********************
"""" TOPICS - SUBROUTINE POOL

DATA Z TYPE I.


FORM SUB1.
  WRITE :/ 'INSIDE SUBROUTINE SUB1 OF ZCORE_D21_P3'.


ENDFORM.


FORM SUB2 USING X Y.
  Z = X + Y.
  WRITE :/ 'SUM IS :',Z.

ENDFORM.

FORM SUB3 USING X Y.
  Z = X - Y.
  WRITE :/ 'DIFFERENCE IS :',Z.

ENDFORM.
