REPORT ZCORE_D23_P1.

****************** DAY 23 PROG 1 **************************

"""" TOPICS - FUNCTION MODULE, IMPORT PARAMETER, EXPORT PARAMETER, CHANGING PARAMETER, EXCEPTIONS.



"""" NOTE - EXPORT PARAMETERS ARE ALWAYS OPTIONAL

PARAMETERS : P_X TYPE I,           """" FOR IMPORTING PARAMETERS IN FUNCTION MODULE
             P_Y TYPE I.


DATA : GV_R1 TYPE I,
       GV_R2 TYPE I.





"""" CALLING CREATED FUNCTION MODULE USING PATTERN SO THAT SIGNATURE IS AUTOMATICALLY GENERATED.

CALL FUNCTION 'ZCORE_D23_P2'
  EXPORTING
    i_x           = P_X
    i_y           = P_Y
 IMPORTING                                  """" EXPORT PARAMETERS IN FUNCTION MODULE ARE ALWAYS OPTIONAL
   E_R1          = GV_R1
   E_R2          = GV_R2.

FORMAT COLOR 1.
WRITE :/ 'SUM IS ', GV_R1.
WRITE :/ 'DIFFERENCE IS ', GV_R2.
FORMAT COLOR OFF.


ULINE.

FORMAT COLOR 2.
WRITE :/ 'CALLING FUNCTION MODULE ZCORE_D23_P3.'.             """" NOTE - DON'T DIRECTLY CALL THE FUNCTION MODULE BEFORE CALLING THE FUNCTION MODULE CHECK THE SIGNATURE OF THE FUNCTION MODULE

CALL FUNCTION 'ZCORE_D23_P3'
  EXPORTING
    i_x           = P_X
  changing
    c_y           = P_Y.

WRITE :/ 'THE SUM OF C_Y = I_X + C_Y IS ',P_Y.

FORMAT COLOR OFF.


"""" NOTE - EXPORT WE WILL GO FOR WHEN WE WANT TO RETURN THE VALUE TO SEPARATE VARIBLE.


"""" IN FUNCTION MODULE TABLES IS INTERNAL TABLE.


"""" NOTE- CAN DEFINE THE EXCEPTION IN THE SAME WAY AND DEFINE EXCEPTION FOR ANY UNKNOWN ERRORS - LIKE DIVIDING ANY NUMBER BY ZERO IT WILL CAUSE RUNTIME ERROR THUS AVOIDING SUCH ERRORS BY HANDLING THEM THROUGH EXCEPTIONS.


